// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAORm75Lz-Y8371P5r2OBVEXyY_yKr05eo',
    appId: '1:805155908250:web:4a7def021b9dc969a24d23',
    messagingSenderId: '805155908250',
    projectId: 'shopeaz-17',
    authDomain: 'shopeaz-17.firebaseapp.com',
    storageBucket: 'shopeaz-17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrdGZ8jfbyjz49OP22V7KRdJvFmwcw7wI',
    appId: '1:805155908250:android:14680a3a6984e178a24d23',
    messagingSenderId: '805155908250',
    projectId: 'shopeaz-17',
    storageBucket: 'shopeaz-17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbRTsl-Miax4HNcfPqwhkad5nyE-1mHw',
    appId: '1:805155908250:ios:ddc415aad984a763a24d23',
    messagingSenderId: '805155908250',
    projectId: 'shopeaz-17',
    storageBucket: 'shopeaz-17.appspot.com',
    iosClientId: '805155908250-f4vd54n84t3maiv4cm2e322a45p7t6t9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
  );
}
